### ISSUE TITLE
Blank screen on localhost:3000 even after successful start of the process

### ISSUE THREAD

**Issue by satwinderbanipal** [broadinstitute/wdl-ide#2]
Hi Team, 

I'm running wdl-ide over mac os "local only", I'm able to issue docker-compose up command which is downloading images and bringing up all the components such DB, Cromwell. But somehow I'm getting blank screen at localhost:3000.

I'm not sure whats going wrong here, could you please suggest as in what I need to check here? one error which I can notice while issuing command is as below:

-------------------------------------------------------------------------------------

```
docker_1    | time="2019-08-04T20:11:57.156457000Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nip: can't find device 'br_netfilter'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
docker_1    | time="2019-08-04T20:11:57.217250700Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
docker_1    | time="2019-08-04T20:11:57.288521600Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
docker_1    | time="2019-08-04T20:11:57.800937800Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
docker_1    | time="2019-08-04T20:11:58.077172900Z" level=info msg="Loading containers: done."
docker_1    | time="2019-08-04T20:11:58.234116900Z" level=info msg="Docker daemon" commit=74b1e89e8a graphdriver(s)=overlay2 version=19.03.1
docker_1    | time="2019-08-04T20:11:58.239849600Z" level=info msg="Daemon has completed initialization"
docker_1    | time="2019-08-04T20:11:58.420574000Z" level=info msg="API listen on [::]:2376"
docker_1    | time="2019-08-04T20:11:58.420716900Z" level=info msg="API listen on /var/run/docker.sock"
db_1        | 2019-08-04T20:11:56.774076Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1        | 2019-08-04T20:11:56.774256Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.17) starting as process 1
db_1        | 2019-08-04T20:11:58.841015Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1        | 2019-08-04T20:11:58.845862Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1        | 2019-08-04T20:11:59.019507Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
db_1        | 2019-08-04T20:11:59.140236Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
theia_1     | yarn run v1.16.0
theia_1     | $ /tmp/wdl-language-support/node_modules/.bin/theia start /home/theia/workspace --hostname=0.0.0.0
theia_1     | root INFO Theia app listening on http://0.0.0.0:3000.
cromwell_1  | 2019-08-04 20:12:05,555  INFO  - Running with database db.url = jdbc:mysql://db:3306/cromwell?rewriteBatchedStatements=true
theia_1     | root ERROR Uncaught Exception:  TypeError: Cannot read property 'versions' of undefined
theia_1     | root ERROR TypeError: Cannot read property 'versions' of undefined
theia_1     |     at Request._callback (/tmp/wdl-language-support/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129:55)
theia_1     |     at Request.self.callback (/tmp/wdl-language-support/node_modules/request/request.js:185:22)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at Request.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1161:10)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at IncomingMessage.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1083:12)
theia_1     |     at Object.onceWrapper (events.js:286:20)
theia_1     |     at IncomingMessage.emit (events.js:203:15)
theia_1     |     at endReadableNT (_stream_readable.js:1129:12)
theia_1     |     at process._tickCallback (internal/process/next_tick.js:63:19)
theia_1     | root ERROR Uncaught Exception:  Error: No extension
theia_1     | root ERROR Error: No extension
theia_1     |     at Request._callback (/tmp/wdl-language-support/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:120:44)
theia_1     |     at Request.self.callback (/tmp/wdl-language-support/node_modules/request/request.js:185:22)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at Request.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1161:10)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at IncomingMessage.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1083:12)
theia_1     |     at Object.onceWrapper (events.js:286:20)
theia_1     |     at IncomingMessage.emit (events.js:203:15)
theia_1     |     at endReadableNT (_stream_readable.js:1129:12)
theia_1     |     at process._tickCallback (internal/process/next_tick.js:63:19)
db_1        | mbind: Operation not permitted
cromwell_1  | 2019-08-04 20:12:18,798  INFO  - Successfully acquired change log lock
cromwell_1  | 2019-08-04 20:12:22,896  INFO  - Reading from cromwell.DATABASECHANGELOG
cromwell_1  | 2019-08-04 20:12:23,324  INFO  - Successfully released change log lock
cromwell_1  | 2019-08-04 20:12:23,388  INFO  - Running with database db.url = jdbc:mysql://db:3306/cromwell?rewriteBatchedStatements=true
cromwell_1  | 2019-08-04 20:12:23,654  INFO  - Successfully acquired change log lock
db_1        | mbind: Operation not permitted
cromwell_1  | 2019-08-04 20:12:23,896  INFO  - Reading from cromwell.SQLMETADATADATABASECHANGELOG
cromwell_1  | 2019-08-04 20:12:23,954  INFO  - Successfully released change log lock
cromwell_1  | 2019-08-04 20:12:25,382  WARN  - Unrecognized configuration key(s) for Jes: default-runtime-attributes.maxRetries
cromwell_1  | 2019-08-04 20:12:27,379  INFO  - Slf4jLogger started
cromwell_1  | 2019-08-04 20:12:28,409 cromwell-system-akka.dispatchers.engine-dispatcher-7 INFO  - Workflow heartbeat configuration:
cromwell_1  | {
cromwell_1  |   "cromwellId" : "cromid-163ae8b",
cromwell_1  |   "heartbeatInterval" : "2 minutes",
cromwell_1  |   "ttl" : "10 minutes",
cromwell_1  |   "failureShutdownDuration" : "5 minutes",
cromwell_1  |   "writeBatchSize" : 10000,
cromwell_1  |   "writeThreshold" : 10000
cromwell_1  | }
cromwell_1  | 2019-08-04 20:12:28,929  WARN  - 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
cromwell_1  | 2019-08-04 20:12:28,953 cromwell-system-akka.dispatchers.service-dispatcher-18 INFO  - Metadata summary refreshing every 1 second.
cromwell_1  | 2019-08-04 20:12:29,002 cromwell-system-akka.actor.default-dispatcher-5 INFO  - KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
cromwell_1  | 2019-08-04 20:12:29,015 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
cromwell_1  | 2019-08-04 20:12:29,017 cromwell-system-akka.dispatchers.engine-dispatcher-24 INFO  - JobStoreWriterActor configured to flush with batch size 1000 and process rate 1 second.
cromwell_1  | 2019-08-04 20:12:29,022 cromwell-system-akka.dispatchers.service-dispatcher-16 INFO  - WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
cromwell_1  | 2019-08-04 20:12:29,970 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
cromwell_1  | 2019-08-04 20:12:30,423 cromwell-system-akka.dispatchers.backend-dispatcher-32 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-04 20:12:30,435 cromwell-system-akka.dispatchers.backend-dispatcher-32 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-04 20:12:30,447 cromwell-system-akka.dispatchers.backend-dispatcher-32 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-04 20:12:30,473 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - Running with 3 PAPI request workers
cromwell_1  | 2019-08-04 20:12:34,986 cromwell-system-akka.dispatchers.engine-dispatcher-30 INFO  - Not triggering log of token queue status. Effective log interval = None
cromwell_1  | 2019-08-04 20:12:37,014 cromwell-system-akka.dispatchers.engine-dispatcher-27 INFO  - Cromwell 41-d8e27c1 service started on 0.0.0.0:8000...
```

**Comment by dinvlad** [comment]
Thanks for reporting, I believe this might be caused by one of the plugins (I think that's Docker), which has been broken lately. I may need to disable it for now (it should not affect anything other than ability to edit Dockerfiles inside the IDE). I'd suggest though to also check Theia repo, they might have issues similar to this: https://github.com/theia-ide/theia

**Comment by satwinderbanipal** [comment]
@dinvlad, Thanks for your response!
Yes, I checked on Theia side and even tried with basic Theia image itself. I was able to bring it up successfully for Theia. 

Somehow our Docker-Compose was not getting up properly even though it shows successful completion of the Setup process.

Did you check some of the errors in the above logs? Also, by when you will disable said plugins? so that I can retry on this.

Many Thanks in advance!!

**Comment by satwinderbanipal** [comment]
Attaching full logs:
---------------------------------------------------------------------
```
MacBook-Air:wdl-ide-master$ docker-compose up
Starting wdl-ide-master_docker_1 ... done
Starting wdl-ide-master_db_1     ... done
Starting wdl-ide-master_cromwell_1 ... done
Starting wdl-ide-master_theia_1    ... done
Attaching to wdl-ide-master_docker_1, wdl-ide-master_db_1, wdl-ide-master_cromwell_1, wdl-ide-master_theia_1
docker_1    | Signature ok
docker_1    | subject=CN = docker:dind server
docker_1    | Getting CA Private Key
docker_1    | /certs/server/cert.pem: OK
docker_1    | Signature ok
docker_1    | subject=CN = docker:dind client
docker_1    | Getting CA Private Key
docker_1    | /certs/client/cert.pem: OK
docker_1    | time="2019-08-05T19:33:03.015761303Z" level=info msg="Starting up"
docker_1    | time="2019-08-05T19:33:03.036618650Z" level=warning msg="could not change group /var/run/docker.sock to docker: group docker not found"
docker_1    | time="2019-08-05T19:33:03.050955054Z" level=info msg="libcontainerd: started new containerd process" pid=49
docker_1    | time="2019-08-05T19:33:03.051091575Z" level=info msg="parsed scheme: \"unix\"" module=grpc
docker_1    | time="2019-08-05T19:33:03.051111400Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
docker_1    | time="2019-08-05T19:33:03.051206295Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
docker_1    | time="2019-08-05T19:33:03.051360701Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
docker_1    | time="2019-08-05T19:33:03.054069803Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006fa300, CONNECTING" module=grpc
docker_1    | time="2019-08-05T19:33:03.981919395Z" level=info msg="starting containerd" revision=894b81a4b802e4eb2a91d1ce216b8817763c29fb version=v1.2.6 
docker_1    | time="2019-08-05T19:33:03.985809774Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1 
docker_1    | time="2019-08-05T19:33:03.994121753Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1 
docker_1    | time="2019-08-05T19:33:03.995407400Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
docker_1    | time="2019-08-05T19:33:03.995811968Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1 
docker_1    | time="2019-08-05T19:33:04.097448070Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
docker_1    | time="2019-08-05T19:33:04.097579545Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1 
docker_1    | time="2019-08-05T19:33:04.132981029Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1 
docker_1    | time="2019-08-05T19:33:04.140230340Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1 
docker_1    | time="2019-08-05T19:33:04.140590148Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
docker_1    | time="2019-08-05T19:33:04.140608391Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1 
docker_1    | time="2019-08-05T19:33:04.140638741Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
docker_1    | time="2019-08-05T19:33:04.140647446Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "ip: can't find device 'aufs'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n": exit status 1" 
docker_1    | time="2019-08-05T19:33:04.140655490Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
docker_1    | time="2019-08-05T19:33:04.146066227Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1 
docker_1    | time="2019-08-05T19:33:04.146150351Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1 
docker_1    | time="2019-08-05T19:33:04.146343179Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146361119Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146374195Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146385713Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146396040Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146406037Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146415769Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.146425938Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1 
docker_1    | time="2019-08-05T19:33:04.146585159Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2 
docker_1    | time="2019-08-05T19:33:04.146668443Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1 
docker_1    | time="2019-08-05T19:33:04.149679502Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1 
docker_1    | time="2019-08-05T19:33:04.149807700Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1 
docker_1    | time="2019-08-05T19:33:04.149981032Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.149998958Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150009581Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150031673Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150115866Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150128046Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150138253Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150249478Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.150264370Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1 
docker_1    | time="2019-08-05T19:33:04.153245550Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.153394545Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.153566267Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.153765857Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1 
docker_1    | time="2019-08-05T19:33:04.161533773Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock" 
docker_1    | time="2019-08-05T19:33:04.161683036Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock" 
docker_1    | time="2019-08-05T19:33:04.161696615Z" level=info msg="containerd successfully booted in 0.187165s" 
docker_1    | time="2019-08-05T19:33:04.210427328Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006fa300, READY" module=grpc
docker_1    | time="2019-08-05T19:33:04.271617480Z" level=info msg="parsed scheme: \"unix\"" module=grpc
docker_1    | time="2019-08-05T19:33:04.272690392Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
docker_1    | time="2019-08-05T19:33:04.273559532Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
docker_1    | time="2019-08-05T19:33:04.273577190Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
docker_1    | time="2019-08-05T19:33:04.274119662Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006fb020, CONNECTING" module=grpc
docker_1    | time="2019-08-05T19:33:04.292536140Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006fb020, READY" module=grpc
docker_1    | time="2019-08-05T19:33:04.300373144Z" level=info msg="parsed scheme: \"unix\"" module=grpc
docker_1    | time="2019-08-05T19:33:04.300440366Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
docker_1    | time="2019-08-05T19:33:04.300506449Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] }" module=grpc
docker_1    | time="2019-08-05T19:33:04.300537179Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
docker_1    | time="2019-08-05T19:33:04.300631373Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001584d0, CONNECTING" module=grpc
docker_1    | time="2019-08-05T19:33:04.302565784Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001584d0, READY" module=grpc
docker_1    | time="2019-08-05T19:33:04.586739158Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
docker_1    | time="2019-08-05T19:33:04.666571504Z" level=info msg="Loading containers: start."
docker_1    | time="2019-08-05T19:33:04.737872042Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: ip: can't find device 'bridge'\nip: can't find device 'br_netfilter'\nmodprobe: can't change directory to '/lib/modules': No such file or directory\n, error: exit status 1"
docker_1    | time="2019-08-05T19:33:04.795204640Z" level=warning msg="Running modprobe nf_nat failed with message: `ip: can't find device 'nf_nat'\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
docker_1    | time="2019-08-05T19:33:04.851420887Z" level=warning msg="Running modprobe xt_conntrack failed with message: `ip: can't find device 'xt_conntrack'\nmodprobe: can't change directory to '/lib/modules': No such file or directory`, error: exit status 1"
docker_1    | time="2019-08-05T19:33:05.450131103Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
docker_1    | time="2019-08-05T19:33:05.660628409Z" level=info msg="Loading containers: done."
docker_1    | time="2019-08-05T19:33:05.815252844Z" level=info msg="Docker daemon" commit=74b1e89e8a graphdriver(s)=overlay2 version=19.03.1
docker_1    | time="2019-08-05T19:33:05.818309827Z" level=info msg="Daemon has completed initialization"
docker_1    | time="2019-08-05T19:33:06.023835387Z" level=info msg="API listen on [::]:2376"
docker_1    | time="2019-08-05T19:33:06.024056687Z" level=info msg="API listen on /var/run/docker.sock"
theia_1     | yarn run v1.16.0
db_1        | 2019-08-05T19:33:04.841280Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1        | 2019-08-05T19:33:04.841545Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.17) starting as process 1
db_1        | 2019-08-05T19:33:07.284643Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1        | 2019-08-05T19:33:07.300170Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1        | 2019-08-05T19:33:07.430704Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
theia_1     | $ /tmp/wdl-language-support/node_modules/.bin/theia start /home/theia/workspace --hostname=0.0.0.0
db_1        | 2019-08-05T19:33:07.663347Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
cromwell_1  | 2019-08-05 19:33:11,723  INFO  - Running with database db.url = jdbc:mysql://db:3306/cromwell?rewriteBatchedStatements=true
theia_1     | root INFO Theia app listening on http://0.0.0.0:3000.
theia_1     | root ERROR Uncaught Exception:  TypeError: Cannot read property 'versions' of undefined
theia_1     | root ERROR TypeError: Cannot read property 'versions' of undefined
theia_1     |     at Request._callback (/tmp/wdl-language-support/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129:55)
theia_1     |     at Request.self.callback (/tmp/wdl-language-support/node_modules/request/request.js:185:22)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at Request.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1161:10)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at IncomingMessage.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1083:12)
theia_1     |     at Object.onceWrapper (events.js:286:20)
theia_1     |     at IncomingMessage.emit (events.js:203:15)
theia_1     |     at endReadableNT (_stream_readable.js:1129:12)
theia_1     |     at process._tickCallback (internal/process/next_tick.js:63:19)
theia_1     | root ERROR Uncaught Exception:  Error: No extension
theia_1     | root ERROR Error: No extension
theia_1     |     at Request._callback (/tmp/wdl-language-support/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:120:44)
theia_1     |     at Request.self.callback (/tmp/wdl-language-support/node_modules/request/request.js:185:22)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at Request.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1161:10)
theia_1     |     at Request.emit (events.js:198:13)
theia_1     |     at IncomingMessage.<anonymous> (/tmp/wdl-language-support/node_modules/request/request.js:1083:12)
theia_1     |     at Object.onceWrapper (events.js:286:20)
theia_1     |     at IncomingMessage.emit (events.js:203:15)
theia_1     |     at endReadableNT (_stream_readable.js:1129:12)
theia_1     |     at process._tickCallback (internal/process/next_tick.js:63:19)
db_1        | mbind: Operation not permitted
cromwell_1  | 2019-08-05 19:33:22,331  INFO  - Successfully acquired change log lock
cromwell_1  | 2019-08-05 19:33:25,180  INFO  - Reading from cromwell.DATABASECHANGELOG
cromwell_1  | 2019-08-05 19:33:25,494  INFO  - Successfully released change log lock
cromwell_1  | 2019-08-05 19:33:25,535  INFO  - Running with database db.url = jdbc:mysql://db:3306/cromwell?rewriteBatchedStatements=true
cromwell_1  | 2019-08-05 19:33:25,801  INFO  - Successfully acquired change log lock
db_1        | mbind: Operation not permitted
cromwell_1  | 2019-08-05 19:33:26,033  INFO  - Reading from cromwell.SQLMETADATADATABASECHANGELOG
cromwell_1  | 2019-08-05 19:33:26,098  INFO  - Successfully released change log lock
cromwell_1  | 2019-08-05 19:33:27,020  WARN  - Unrecognized configuration key(s) for Jes: default-runtime-attributes.maxRetries
cromwell_1  | 2019-08-05 19:33:28,013  INFO  - Slf4jLogger started
cromwell_1  | 2019-08-05 19:33:28,588 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - Workflow heartbeat configuration:
cromwell_1  | {
cromwell_1  |   "cromwellId" : "cromid-73e03d4",
cromwell_1  |   "heartbeatInterval" : "2 minutes",
cromwell_1  |   "ttl" : "10 minutes",
cromwell_1  |   "failureShutdownDuration" : "5 minutes",
cromwell_1  |   "writeBatchSize" : 10000,
cromwell_1  |   "writeThreshold" : 10000
cromwell_1  | }
cromwell_1  | 2019-08-05 19:33:29,133 cromwell-system-akka.dispatchers.service-dispatcher-14 INFO  - Metadata summary refreshing every 1 second.
cromwell_1  | 2019-08-05 19:33:29,238 cromwell-system-akka.dispatchers.engine-dispatcher-28 INFO  - JobStoreWriterActor configured to flush with batch size 1000 and process rate 1 second.
cromwell_1  | 2019-08-05 19:33:29,240 cromwell-system-akka.actor.default-dispatcher-7 INFO  - KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
cromwell_1  | 2019-08-05 19:33:29,241 cromwell-system-akka.dispatchers.service-dispatcher-15 INFO  - WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
cromwell_1  | 2019-08-05 19:33:29,258 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
cromwell_1  | 2019-08-05 19:33:29,265  WARN  - 'docker.hash-lookup.gcr-api-queries-per-100-seconds' is being deprecated, use 'docker.hash-lookup.gcr.throttle' instead (see reference.conf)
cromwell_1  | 2019-08-05 19:33:29,599 cromwell-system-akka.dispatchers.engine-dispatcher-32 INFO  - JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
cromwell_1  | 2019-08-05 19:33:29,875 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-05 19:33:29,883 cromwell-system-akka.dispatchers.backend-dispatcher-33 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-05 19:33:29,893 cromwell-system-akka.dispatchers.backend-dispatcher-35 INFO  - PAPI request worker batch interval is 666 milliseconds
cromwell_1  | 2019-08-05 19:33:29,914 cromwell-system-akka.dispatchers.backend-dispatcher-34 INFO  - Running with 3 PAPI request workers
cromwell_1  | 2019-08-05 19:33:33,183 cromwell-system-akka.dispatchers.engine-dispatcher-9 INFO  - Cromwell 41-d8e27c1 service started on 0.0.0.0:8000...
cromwell_1  | 2019-08-05 19:33:34,574 cromwell-system-akka.dispatchers.engine-dispatcher-29 INFO  - Not triggering log of token queue status. Effective log interval = None
```

**Comment by satwinderbanipal** [comment]
@dinvlad, any updates please, I tried downloading afresh but facing same issue again as explained above. Can you please help me out here?

**Comment by dinvlad** [comment]
Sorry for the delay - I've just released a new version that addresses the blank screen issue. Could you please confirm if that works?

(You may need to run `docker-compose pull && docker-compose up`)

**Comment by satwinderbanipal** [comment]
Hi @dinvlad, Thanks for the response!!

As suggested by you, I tried downloading and running docker-compose but it's still showing a blank screen for http://localhost:3000/

Hereby attaching docker-compose up logs for your reference. Can you please check it once and help me out.
[Logs-output.txt](https://github.com/broadinstitute/wdl-ide/files/3535441/Logs-output.txt)

Regards
Satwinder Singh

**Comment by dinvlad** [comment]
Could you please try running *docker-compose pull && docker-compose up* as
suggested above?

**Comment by satwinderbanipal** [comment]
@dinvlad thank you so much...I was missing on this point. 
Now, I'm able to bring it up in my browser!!!

Just want to check with you if there is any basic documentation to create some sample workflow and run on this package. It will help newcomers as in how to design and run tasks on Theia+Cromwell IDE.

**Comment by dinvlad** [comment]
Yes, thanks for the suggestion! I'm planning to work on better documentation.
